name: myapp
description: "A new Flutter project for Mueblería Carrasco."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Conexión para Mueblería Carrasco
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Si vas a usar una calaverita animada, recuerda descomentar la sección de assets abajo
  # assets:
  #   - assets/calaverita.json